name: CD
on:
  pull_request:
    types: [closed]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: variantdev/mod
      uses: variantdev/mod-action@v0.6.2
 
    - name: Make dist
      run: make publish $GITHUB_TOKEN
