name: CI
on: push
#  pull_request:
#    types: [closed]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: variantdev/mod
      uses: variantdev/mod-action@v0.6.2
 
    - name: Make dist
      if: github.base_ref	== "master" && event.pull_request.merged == true
      run: make dist $GITHUB_TOKEN
