name: build-develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build CLI Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Makefile local golang build
        run: make local

      - name: Makefile + Dockerfile docker build
        run: make build

      # Produces the binaries at the directory ./dist
      - name: Makefile + Dockerfile docker dist
        run: make dist

      # https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow
      - name: Upload MacOS Binary
        uses: actions/upload-artifact@v2
        with:
          name: cloner-darwin-amd64
          path: dist/cloner-darwin-amd64

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v2
        with:
          name: cloner-linux-amd64
          path: dist/cloner-linux-amd64

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v2
        with:
          name: cloner-windows-amd64.exe
          path: dist/cloner-windows-amd64.exe