name: build-develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Makefile local golang build
        run: make local

      - name: Makefile + Dockerfile docker build
        run: make build
