name: build-develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build CLI Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Makefile local golang build
        run: make local

      - name: Makefile + Dockerfile docker build
        run: make build

      # https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow
      - name: Upload Built Binaries
        uses: actions/upload-artifact@v2
        with:
          name: Distribution Binaries
          path: dist