name: release-master

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # https://github.com/actions/checkout/pull/258 needs to fetch all tags
          fetch-depth: 0

      - name: Makefile + Dockerfile dockerized release
        env:
          PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
        run: make release

